-- SOME BASIC COMMANDS

-- CREATE USER
CREATE USER myuser WITH PASSWORD 'mypassword';

-- DROP USER
DROP USER myuser;

-- ALTER USER
ALTER USER myuser WITH PASSWORD 'newpassword';

-- GRANT PRIVILEGES TO USER
GRANT ALL PRIVILEGES ON DATABASE mydb TO myuser;

-- REVOKE PRIVILEGES FROM USER
REVOKE ALL PRIVILEGES ON DATABASE mydb FROM myuser;

-- COMMAND TO CREATE DATABASE
CREATE DATABASE mydb WITH OWNER myuser;

-- COMMAND TO DROP DATABASE
DROP DATABASE mydb;

-- COMMAND TO ALTER DATABASE
ALTER DATABASE mydb OWNER TO myuser;

-- COMMAND TO LIST DATABASES
\l

-- COMMAND TO CONNECT TO DATABASE
\c mydb

-- COMMAND TO LIST TABLES
\dt

-- COMMAND TO LIST VIEWS
\dv

-- COMMAND TO LIST FUNCTIONS
\df
